version: "3.8"

services:
    app_one:
      build: .
      environment:
       - INSTANCE_NAME=app_one
       - PORT=5010

    app_two:
      build: .
      environment:
       - INSTANCE_NAME=app_two
       - PORT=5020

    app_three:
      build: .
      environment:
       - INSTANCE_NAME=app_three
       - PORT=5030
    
    nginx:
      image: nginx:latest 
      ports:
        - "8080:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - app_one
        - app_two
        - app_three