events {}

http {
  upstream backend_cluster {
    server app_one:5010;
    server app_two:5020;
  }

  server {
    listen 80;
    server_name localhost;

    location / {
      proxy_pass http://backend_cluster;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}